### ISSUE TITLE
天气支持逐小时预报

### ISSUE THREAD

**Issue by MKStoler4096** [Return-Log/Education-Clock#1]
主要是现在没有一款软件能预报降水和逐小时天气

**Comment by Return-Log** [comment]
天气API目前使用的是OpenWeather，现在使用的免费api可以报实时天气，和未来每三小时天气。其实是够用的，天气不会变的那么快，如果是付费api可以未来每小时天气，但只是为了桌面显示不是很划算。
- 祝你愉快！

**Comment by Return-Log** [comment]
版本v0.7 我记得是显示一天中每个三小时天气，不过界面很丑
