### ISSUE TITLE
IMAP 程序执行失败

### ISSUE THREAD

**Issue by njmd2203** [Return-Log/Education-Clock#2]
![image](https://github.com/user-attachments/assets/8ddb157a-5493-4d1a-aa83-8c2a94b79063)
**IMAP 程序执行失败，从wireshark抓包的数据看，应该是outlook.com的返回值有问题("LOGIN FAILED")**
![image](https://github.com/user-attachments/assets/f90140ed-65d1-403f-9acb-74bdea8da2b7)
可以换一个库或者用C重写一下代码逻辑
除此之外，希望可以增加进入控制面板的代码，以免可爱的同学们进行某些破坏活动
（用一个json存储一下密码应该就行了）

**Comment by Return-Log** [comment]
谢谢你的回复，初次使用需要在data文件夹下将邮箱更换为自己的

**Comment by Return-Log** [comment]
此外最新版本存在bug，请先使用上一版本，我正在进行整个项目的重构
